### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "internmap/src/index.js". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by voitje** [mbostock/internmap#1]
Hello! I used d3 array. I have updated the library from 2.9.0 to 2.11.0.
![image](https://user-images.githubusercontent.com/36591363/106697981-726b2100-6612-11eb-93f1-773cf5f6ef8e.png)
I think this is due to the addition of the new Intermap library. In `src\index.js` ` export {InternMap, InternSet} from "internmap"`;

**Comment by mbostock** [comment]
You must be using some sort of bundler that is generating a broken import. The provided d3-array bundles include InternMap directly, while the source file imports from the base module specifier “internmap”, not “internmap/arc/index.is”.
